config/routes.rb
Rails.application.routes.draw do
  get 'quizzes/home'
  get 'quizzes/quizz'
  get 'quizzes/results'
  
  get '/home', to: 'quizzes#home'
  get '/quizz', to: 'quizzes#quizz'
  get '/results', to: 'quizzes#results'
  
  get "begin", :controller=> "home"
  post "submit", :controller=>"submit"
  post "/quizzes/quizz", :controller=>"quizz"
  
  root 'quizzes#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/quiz.rb
class Quiz < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  $count = 0
  $score = 0
  def begin
    $count += 1
    @que = Quiz.find($count)
    @question = @que.question
    @answers = @que.answers
  end
  
  def submit
    @s_key = params[:option]
    c_hash = eval(@correct_answers)
    c_hash.each do |k, v|
      if k[0...8] == @s_key[0...8] and v == true
        $score += 1
      end
    end
    $count += 1
    
    @que = Quiz.find($count + 1)
    @question = @que.question
    @answers = @que.answers
    

    if (count == 10)
      QuizzesController::results
    end
  end
  
  def quizz
    
    @que = Quiz.find($count + 1)
    @question = @que.question
    @answers = @que.answers
    @correct_answers = @que.correct_answers
  end
  
  
  def self.results
    
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
    <p>Highest Level Achieved: PA</p>
    <nav>
        <ul>
            <li><a href="https://www.facebook.com/">Facebook</a></li>
            <li><a href="https://twitter.com/home">Twitter</a></li>
            <li><a href="https://www.linkedin.com/home">LinkedIn</a></li>
        </ul>
    </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
        <nav>
            <ul class="nav navbar-nav navbar-right">
                <li>Name: Jia Bang Vuong</li></br>
                <li>Email: s3785886@student.rmit.edu.au</li>
            </ul>
        </nav>
    </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QuizPlus</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/quizzes/home.html.erb
<% provide(:title, "Home") %>
<div> 
    <h1>QuizPages#home</h1>
    <p>Are you ready to start the quiz?</p>
    <%= button_to "Yes", quizzes_quizz_url, :method => "get"  %>

</div>

app/views/quizzes/quizz.html.erb
<% provide(:title, "Quizz") %>

<div id="questions">
        <%= form_tag do %>
            <h3><%= @question %></h3>
            <%- hash = eval(@answers) %>
            <%- hash.each do |k, v|  %>
                <!--<input type="radio" id="option" name="option" value="option">-->
                <!--<label for="option"><%- puts '#{v}' unless nil %></label><br>-->
                <%- @data = hash.key(v) %>
                <%= radio_button_tag k, hash.key(v), false if v != nil%>
                <%= v %></br>
                
            <%- end %>
            <%= button_to "Submit", :method=> 'submit', :option => @data, remote: true %>
        <% end %>
</div>

app/views/quizzes/results.html.erb
<div class="center jumbotron">
    You have scored <%= $score %> out of ten.
</div>